language: ruby
cache: bundler
before_install:
  - gem install bundler
install:
  - bundle update
script: xvfb-run bundle exec rake
rvm:
  - 2.0.0
  - 2.1.9
  - 2.2.5
  - 2.3.1
  - ruby-head
  - jruby-head
  - rbx-2
branches:
  only:
    - master
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-2
